
(function(){
'use strict';
const root=window.CABW_CONTRACTS_DATA||{records:[],summary:{}}; const records=Array.isArray(root.records)?root.records:[]; const summary=root.summary||{};
const $=(s,c)=> (c||document).querySelector(s); const $all=(s,c)=>Array.from((c||document).querySelectorAll(s));
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const money=v=>'US$ '+Number(v||0).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});
const num=v=>Number(v||0).toLocaleString('pt-BR');
function selected(sel){if(!sel)return []; return Array.from(sel.selectedOptions).map(o=>o.value).filter(Boolean);}
function unique(a){return Array.from(new Set(a.filter(v=>v!==undefined&&v!==null&&String(v).trim()!==''))).sort((a,b)=>String(a).localeCompare(String(b),'pt-BR'));}

function ensureCabwMultiCss(){
  if(document.getElementById('cabw-multi-dropdown-css')) return;
  const st=document.createElement('style'); st.id='cabw-multi-dropdown-css';
  st.textContent=`
  select.cabw-native-multi-hidden{display:none!important;}
  .cabw-multi-dropdown{position:relative;width:100%;font-family:inherit;}
  .cabw-multi-button{width:100%;min-height:46px;border:1px solid #ccd6e6;border-radius:10px;background:#f8fbff;color:#001f55;padding:10px 42px 10px 14px;text-align:left;font-weight:500;box-shadow:inset 0 1px 0 rgba(255,255,255,.75);cursor:pointer;line-height:1.25;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;}
  .cabw-multi-button:after{content:'▾';position:absolute;right:14px;top:50%;transform:translateY(-50%);font-size:15px;color:#003b7a;pointer-events:none;}
  .cabw-multi-dropdown.open .cabw-multi-button{border-color:#f5c400;box-shadow:0 0 0 .2rem rgba(245,196,0,.18);background:#fff;}
  .cabw-multi-menu{display:none;position:absolute;z-index:3000;left:0;right:0;top:calc(100% + 6px);max-height:300px;overflow:auto;background:#fff;border:1px solid #ccd6e6;border-radius:12px;box-shadow:0 14px 32px rgba(0,31,85,.18);padding:6px;}
  .cabw-multi-dropdown.open .cabw-multi-menu{display:block;}
  .cabw-multi-option{display:flex;gap:9px;align-items:flex-start;padding:8px 9px;border-radius:8px;color:#001f55;font-size:14px;line-height:1.25;cursor:pointer;margin:0;}
  .cabw-multi-option:hover{background:#eef5ff;}
  .cabw-multi-option input{margin-top:2px;accent-color:#003b7a;flex:0 0 auto;}
  .cabw-multi-actions{display:flex;justify-content:space-between;gap:8px;border-bottom:1px solid #e7edf6;margin-bottom:4px;padding:4px 4px 8px;position:sticky;top:0;background:#fff;z-index:1;}
  .cabw-multi-actions button{border:0;border-radius:8px;background:#e9eef6;color:#003b7a;font-weight:700;padding:5px 8px;font-size:12px;cursor:pointer;}
  .cabw-multi-actions button:hover{background:#dce6f2;}
  .cabw-multi-empty{padding:10px;color:#6c7890;font-size:13px;}
  /* checkbox-proportional-fix */
  .detail-field .cabw-multi-option input[type="checkbox"],.contracts-field .cabw-multi-option input[type="checkbox"],.cabw-multi-option input[type="checkbox"]{appearance:auto!important;-webkit-appearance:checkbox!important;width:18px!important;min-width:18px!important;max-width:18px!important;height:18px!important;min-height:18px!important;max-height:18px!important;padding:0!important;margin:1px 7px 0 0!important;border:1px solid #8fa2bd!important;border-radius:3px!important;background:#fff!important;box-shadow:none!important;flex:0 0 18px!important;transform:none!important;accent-color:#003b7a!important;}
  .cabw-multi-menu{box-sizing:border-box!important;width:100%!important;min-width:100%!important;max-width:min(760px,calc(100vw - 32px))!important;max-height:260px!important;overflow-y:auto!important;overflow-x:auto!important;}
  .cabw-multi-option{display:flex!important;align-items:flex-start!important;gap:8px!important;padding:7px 8px!important;font-size:13px!important;line-height:1.25!important;}
  .cabw-multi-option span{display:block;min-width:0;white-space:nowrap;overflow:visible;}
  .cabw-multi-actions button{min-height:28px!important;width:auto!important;min-width:0!important;padding:5px 10px!important;}

  .cabw-multi-filter-line{display:flex;gap:6px;align-items:center;border-bottom:1px solid #e7edf6;margin-bottom:4px;padding:4px 4px 8px;position:sticky;top:0;background:#fff;z-index:2;}
  .cabw-multi-search{min-width:0;flex:1;border:1px solid #ccd6e6;border-radius:8px;padding:7px 8px;font:inherit;font-size:12px;color:#001f55;background:#f8fbff;}
  .cabw-multi-search-button{border:0;border-radius:8px;background:#003b7a;color:#fff;font-weight:800;padding:7px 9px;font-size:11px;cursor:pointer;white-space:nowrap;}
  .cabw-multi-menu{left:0!important;right:auto!important;width:max-content!important;min-width:min(440px,calc(100vw - 48px))!important;max-width:min(780px,calc(100vw - 48px))!important;overflow-x:auto!important;}
  .cabw-multi-dropdown.cabw-align-right .cabw-multi-menu{left:auto!important;right:0!important;}
  .cabw-multi-option span{white-space:nowrap!important;overflow:visible!important;text-overflow:clip!important;}
  .cabw-multi-actions{display:grid!important;grid-template-columns:1fr 1fr!important;gap:8px!important;}
  .cabw-multi-actions button{width:100%!important;white-space:nowrap!important;padding:7px 10px!important;}
  .contracts-filter-grid{grid-template-columns:repeat(3,minmax(230px,1fr))!important;align-items:end!important;}
  @media(max-width:1320px){.contracts-filter-grid{grid-template-columns:repeat(2,minmax(230px,1fr))!important;}}
  @media(max-width:768px){.contracts-filter-grid{grid-template-columns:1fr!important;}.cabw-multi-menu{min-width:100%!important;max-width:calc(100vw - 32px)!important;}}

  `;
  document.head.appendChild(st);
  document.addEventListener('click',e=>{ if(!e.target.closest('.cabw-multi-dropdown')) document.querySelectorAll('.cabw-multi-dropdown.open').forEach(w=>w.classList.remove('open')); });
}
function multiPlaceholder(sel){
  const label=sel.closest('label'); const span=label?label.querySelector('span'):null; const name=(span?span.textContent.trim():'opções').toLowerCase();
  if(name.includes('empresa')) return 'Todas as empresas';
  if(name.includes('número')) return 'Todos os números';
  if(name.includes('unidade')) return 'Todas as unidades';
  if(name.includes('orden')) return 'Todas as ordenações';
  if(name.includes('grande')) return 'Todos os Grandes Comandos';
  if(name.includes('ação')) return 'Todas as ações';
  if(name.includes('moeda')) return 'Todas as moedas';
  if(name.includes('vigência')) return 'Todas';
  if(name.includes('natureza')) return 'Todas as naturezas';
  if(name.includes('projeto')) return 'Todos os projetos';
  if(name==='om') return 'Todas as OM';
  return 'Todas as opções';
}
function positionCabwMultiMenu(wrap){try{wrap.classList.remove('cabw-align-right'); const menu=wrap.querySelector('.cabw-multi-menu'); if(!menu)return; const r=menu.getBoundingClientRect(); if(r.right>window.innerWidth-16) wrap.classList.add('cabw-align-right');}catch(e){}}
function updateCabwMulti(sel){
  const wrap=sel.nextElementSibling && sel.nextElementSibling.classList && sel.nextElementSibling.classList.contains('cabw-multi-dropdown') ? sel.nextElementSibling : null;
  if(!wrap) return;
  const chosen=Array.from(sel.selectedOptions).map(o=>o.textContent.trim()).filter(Boolean);
  const btn=wrap.querySelector('.cabw-multi-button');
  if(btn){ btn.textContent = chosen.length ? (chosen.length<=2 ? chosen.join(', ') : `${chosen.length} selecionadas`) : multiPlaceholder(sel); btn.title = chosen.join(', '); }
  wrap.querySelectorAll('input[type="checkbox"]').forEach(cb=>{ const opt=Array.from(sel.options).find(o=>o.value===cb.value); cb.checked=!!(opt&&opt.selected); });
}
function rebuildCabwMulti(sel){
  ensureCabwMultiCss();
  sel.multiple=true; sel.size=1; sel.classList.remove('cabw-multi-select'); sel.classList.add('cabw-native-multi-hidden'); sel.setAttribute('aria-hidden','true'); sel.tabIndex=-1;
  let wrap=sel.nextElementSibling && sel.nextElementSibling.classList && sel.nextElementSibling.classList.contains('cabw-multi-dropdown') ? sel.nextElementSibling : null;
  if(!wrap){ wrap=document.createElement('div'); wrap.className='cabw-multi-dropdown'; sel.parentNode.insertBefore(wrap, sel.nextSibling); }
  const options=Array.from(sel.options);
  const menuItems=options.length ? options.map(o=>`<label class="cabw-multi-option"><input type="checkbox" value="${esc(o.value)}" ${o.selected?'checked':''}><span>${esc(o.textContent)}</span></label>`).join('') : '<div class="cabw-multi-empty">Sem opções disponíveis</div>';
  wrap.innerHTML=`<button type="button" class="cabw-multi-button" aria-haspopup="listbox" aria-expanded="false"></button><div class="cabw-multi-menu"><div class="cabw-multi-filter-line"><input type="search" class="cabw-multi-search" data-ms-search placeholder="Texto para selecionar..."><button type="button" class="cabw-multi-search-button" data-ms-action="contains">Selecionar</button></div><div class="cabw-multi-actions"><button type="button" data-ms-action="all">Marcar todas</button><button type="button" data-ms-action="clear">Limpar</button></div>${menuItems}</div>`;
  const btn=wrap.querySelector('.cabw-multi-button');
  btn.addEventListener('click',e=>{e.preventDefault(); e.stopPropagation(); document.querySelectorAll('.cabw-multi-dropdown.open').forEach(w=>{if(w!==wrap)w.classList.remove('open')}); wrap.classList.toggle('open'); btn.setAttribute('aria-expanded',wrap.classList.contains('open')?'true':'false'); if(wrap.classList.contains('open')) setTimeout(()=>positionCabwMultiMenu(wrap),0);});
  btn.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '||e.key==='ArrowDown'){e.preventDefault(); btn.click();}});
  wrap.querySelectorAll('input[type="checkbox"]').forEach(cb=>cb.addEventListener('change',()=>{ const opt=Array.from(sel.options).find(o=>o.value===cb.value); if(opt) opt.selected=cb.checked; updateCabwMulti(sel); sel.dispatchEvent(new Event('change',{bubbles:true})); }));
  const searchInput=wrap.querySelector('[data-ms-search]'); const filterOptions=()=>{const q=(searchInput?.value||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,''); wrap.querySelectorAll('.cabw-multi-option').forEach(label=>{const txt=(label.textContent||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,''); label.style.display=!q||txt.includes(q)?'flex':'none';});}; searchInput?.addEventListener('input',filterOptions); searchInput?.addEventListener('click',e=>e.stopPropagation()); wrap.querySelector('[data-ms-action="contains"]')?.addEventListener('click',e=>{e.preventDefault(); e.stopPropagation(); const q=(searchInput?.value||'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,''); if(!q)return; Array.from(sel.options).forEach(o=>{const t=(o.textContent||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,''); if(t.includes(q)) o.selected=true;}); updateCabwMulti(sel); sel.dispatchEvent(new Event('change',{bubbles:true}));});
  wrap.querySelector('[data-ms-action="all"]')?.addEventListener('click',e=>{e.preventDefault(); Array.from(sel.options).forEach(o=>o.selected=true); updateCabwMulti(sel); sel.dispatchEvent(new Event('change',{bubbles:true}));});
  wrap.querySelector('[data-ms-action="clear"]')?.addEventListener('click',e=>{e.preventDefault(); Array.from(sel.options).forEach(o=>o.selected=false); updateCabwMulti(sel); sel.dispatchEvent(new Event('change',{bubbles:true}));});
  updateCabwMulti(sel);
}
function updateAllCabwMultis(){document.querySelectorAll('select.cabw-native-multi-hidden').forEach(updateCabwMulti);}

function fillMulti(sel, vals){if(!sel)return; const old=selected(sel); sel.multiple=true; sel.innerHTML=vals.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join(''); if(old.length){old.forEach(v=>{const o=Array.from(sel.options).find(o=>o.value===v); if(o)o.selected=true;});} else {Array.from(sel.options).forEach(o=>o.selected=false);} rebuildCabwMulti(sel);}
function dateBr(s){if(!s)return '—'; const [y,m,d]=String(s).split('-'); return d&&m&&y?`${d}/${m}/${y}`:'—';}
function daysToEnd(r){if(!r.dataFinal)return null; const end=new Date(r.dataFinal+'T00:00:00'); const now=new Date(); now.setHours(0,0,0,0); return Math.ceil((end-now)/(1000*60*60*24));}
function vigenciaBucket(r){const d=daysToEnd(r); if(d===null||Number.isNaN(d)) return 'Sem data final'; if(d<0) return 'Vigência expirada'; if(d<=90) return 'Vencimento em até 90 dias'; if(d<=150) return 'Vencimento entre 90 e 150 dias'; return 'Vencimento acima de 150 dias';}
function risk(r){const d=daysToEnd(r); if(d===null||Number.isNaN(d)) return ''; if(d<0)return 'VENCIDO'; if(d<=90)return 'RISCO'; return '';}
function catRows(cat){return records.filter(r=>!cat||r.category===cat);}
function agg(rows){const paid=rows.reduce((a,r)=>a+Number(r.totalEmpenhadoUsd||0),0), billed=rows.reduce((a,r)=>a+Number(r.totalFaturadoUsd||0),0); return {count:rows.length,value:rows.reduce((a,r)=>a+Number(r.valorContrato||0),0),paid:paid,billed:billed,toBill:paid-billed,available:rows.reduce((a,r)=>a+Number(r.valorAEmpenhar||0),0)};}
function filters(){return {numero:selected($('#filterNumeroContrato')), empresa:selected($('#filterEmpresa')), unidade:selected($('#filterUnidade')), gc:selected($('#filterGrandeComando')), ordenador:selected($('#filterOrdenador')), acao:selected($('#filterAcao')), moeda:selected($('#filterMoeda')), status:selected($('#filterStatus')), valueRange:selected($('#filterValueRange')), search:($('#filterContratoSearch')?.value||'').trim().toLowerCase()};}
function has(sel,val){return !sel.length||sel.includes(val||'');}
function valueRangeBucket(v){v=Number(v||0); if(v<=10000)return 'até US$ 10,000.00'; if(v<=50000)return 'entre US$ 10,000.00 e US$ 50,000.00'; if(v<=1000000)return 'Entre US$ 50,000.00 e US$ 1,000,000.00'; return 'Acima de US$ 1,000,000.00';}
const valueRangeOptions=['até US$ 10,000.00','entre US$ 10,000.00 e US$ 50,000.00','Entre US$ 50,000.00 e US$ 1,000,000.00','Acima de US$ 1,000,000.00'];
const poDetails=root.poDetails||root.purchaseOrdersByContract||{};
function poDateValue(s){return String(s||'');}
function formatDateIso(s){if(!s)return '—'; const p=String(s).slice(0,10).split('-'); return p.length===3?`${p[2]}/${p[1]}/${p[0]}`:String(s);}
function poRowsForContracts(rows){const arr=[]; rows.forEach(r=>{(poDetails[String(r.contrato||'').trim()]||[]).forEach(p=>arr.push(Object.assign({contrato:r.contrato,numeroContrato:r.numero},p)));}); return arr.sort((a,b)=>poDateValue(b.data).localeCompare(poDateValue(a.data)));}

function ensureInvoiceMonthlySection(){let sec=$('#contractsInvoiceMonthlySection'); if(sec)return sec; const tableSec=$('#contractsTable')?.closest('.contracts-table-card'); if(!tableSec)return null; tableSec.insertAdjacentHTML('afterend','<section class="contracts-table-card" id="contractsInvoiceMonthlySection" aria-label="Faturamento mensal por contrato"><div class="contracts-table-toolbar"><h2>Faturamento mensal por PO associada</h2><span>Valores faturados por mês nas POs vinculadas aos contratos filtrados</span></div><div id="contractsInvoiceMonthlyChart" style="min-height:360px"></div></section>'); return $('#contractsInvoiceMonthlySection');}
function invoiceDetailLabel(items){
  if(!items||!items.length)return 'Sem faturas no mês';
  const grouped=new Map();
  items.forEach(it=>{const fat=String(it.fatura||'Sem fatura').trim()||'Sem fatura'; const po=String(it.po||'').trim(); const k=fat+'|'+po; const cur=grouped.get(k)||{fatura:fat,po:po,valor:0}; cur.valor+=Number(it.valor||0); grouped.set(k,cur);});
  const arr=Array.from(grouped.values()).sort((a,b)=>String(a.fatura).localeCompare(String(b.fatura),'pt-BR')||String(a.po).localeCompare(String(b.po),'pt-BR'));
  const max=28;
  const lines=arr.slice(0,max).map(it=>`${esc(it.fatura)}${it.po?' / PO '+esc(it.po):''}: ${money(it.valor)}`);
  if(arr.length>max) lines.push(`... mais ${arr.length-max} fatura(s)`);
  return lines.join('<br>');
}
function monthlyInvoiceForRows(rows){const meta=root.invoiceMonthlyMeta||{}; const map=root.invoiceMonthlyByContract||{}; const detailMap=root.invoiceMonthlyDetailsByContract||{}; const cur=Array(12).fill(0), prev=Array(12).fill(0); const curDetails=Array.from({length:12},()=>[]), prevDetails=Array.from({length:12},()=>[]); rows.forEach(r=>{const key=String(r.contrato||'').trim(); const rec=map[key]; if(rec){(rec.current||[]).forEach((v,i)=>cur[i]+=Number(v||0)); (rec.previous||[]).forEach((v,i)=>prev[i]+=Number(v||0));} const det=detailMap[key]; if(det){(det.current||[]).forEach((items,i)=>(items||[]).forEach(x=>curDetails[i].push(x))); (det.previous||[]).forEach((items,i)=>(items||[]).forEach(x=>prevDetails[i].push(x)));}}); return {current:cur, previous:prev, currentDetails:curDetails, previousDetails:prevDetails, currentYear:meta.currentYear||new Date().getFullYear(), previousYear:meta.previousYear||((meta.currentYear||new Date().getFullYear())-1)};}
function drawInvoiceMonthlyChart(rows){const sec=ensureInvoiceMonthlySection(); if(!sec)return; const el=$('#contractsInvoiceMonthlyChart'); if(!el)return; const months=['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez']; const d=monthlyInvoiceForRows(rows); const currentHover=d.currentDetails.map(invoiceDetailLabel); const previousHover=d.previousDetails.map(invoiceDetailLabel); const currentText=d.current.map(v=>Math.abs(Number(v||0))>0.005?money(v):''); const avgCurrent=d.current.reduce((a,b)=>a+Number(b||0),0)/12; const avgPrevious=d.previous.reduce((a,b)=>a+Number(b||0),0)/12; let avgBox=document.getElementById('contractsInvoiceAverageBox'); if(!avgBox){avgBox=document.createElement('div'); avgBox.id='contractsInvoiceAverageBox'; avgBox.style.cssText='min-width:210px;border:1px solid #d9e2ef;border-radius:14px;background:#f8fbff;padding:14px 16px;color:#001f55;box-shadow:0 8px 22px rgba(0,31,85,.08);align-self:center'; el.parentNode.insertBefore(avgBox,el.nextSibling);} avgBox.innerHTML='<div style="font-size:12px;font-weight:800;text-transform:uppercase;color:#52627a;margin-bottom:8px">Média mensal faturada</div><div style="margin-bottom:10px"><span style="display:block;font-size:12px;color:#52627a">'+d.currentYear+'</span><strong style="font-size:18px;color:#001f55">'+money(avgCurrent)+'</strong></div><div><span style="display:block;font-size:12px;color:#52627a">'+d.previousYear+'</span><strong style="font-size:18px;color:#6b7280">'+money(avgPrevious)+'</strong></div>'; const parent=el.parentNode; if(parent && !parent.classList.contains('contracts-invoice-layout')){parent.classList.add('contracts-invoice-layout'); parent.style.display='grid'; parent.style.gridTemplateColumns='minmax(0,1fr) 230px'; parent.style.gap='18px'; parent.style.alignItems='stretch';} if(window.Plotly){Plotly.newPlot(el,[{type:'scatter',mode:'lines+markers+text',name:String(d.currentYear),x:months,y:d.current,text:currentText,textposition:'top center',textfont:{color:'#001f55',size:11},cliponaxis:false,customdata:currentHover,line:{color:'#001f55',width:4},marker:{color:'#001f55',size:7},hovertemplate:'%{x}<br>'+d.currentYear+': US$ %{y:,.2f}<br><b>Faturas</b><br>%{customdata}<extra></extra>'},{type:'scatter',mode:'lines+markers',name:String(d.previousYear),x:months,y:d.previous,customdata:previousHover,line:{color:'#8d96a6',width:3},marker:{color:'#8d96a6',size:6},hovertemplate:'%{x}<br>'+d.previousYear+': US$ %{y:,.2f}<br><b>Faturas</b><br>%{customdata}<extra></extra>'}],{height:430,margin:{l:80,r:28,t:48,b:55},yaxis:{title:'US$',autorange:true},xaxis:{type:'category',categoryorder:'array',categoryarray:months},legend:{orientation:'h',x:0,y:1.14},hovermode:'closest'},{displayModeBar:false,responsive:true});}else{el.innerHTML='<p>Plotly não carregado.</p>';}}
function poDetailsTableHtml(rows,reportMode){const pos=poRowsForContracts(rows); const total=pos.reduce((a,p)=>a+Number(p.valorTotalUsd||0),0); const fat=pos.reduce((a,p)=>a+Number(p.valorFaturadoUsd||0),0); const sal=pos.reduce((a,p)=>a+Number(p.saldoUsd||0),0); const totalRow=`<tr class="po-total-row" style="font-weight:800;background:#eef3fa;color:#00265f"><td colspan="6">Total das POs listadas</td><td class="text-right">${money(total)}</td><td class="text-right">${money(fat)}</td><td class="text-right">${money(sal)}</td></tr>`; const dataRows=pos.map(p=>`<tr><td>${esc(p.contrato)}</td><td>${esc(p.numeroContrato)}</td><td>${esc(p.po)}</td><td>${formatDateIso(p.data)}</td><td>${esc(p.fornecedor)}</td><td>${esc(p.objetoResumo||p.projeto||"")}</td><td class="text-right">${money(p.valorTotalUsd)}</td><td class="text-right">${money(p.valorFaturadoUsd)}</td><td class="text-right">${money(p.saldoUsd)}</td></tr>`).join('') || '<tr><td colspan="9">Nenhuma PO encontrada para os contratos filtrados.</td></tr>'; const table=`<table class="contracts-table"><thead><tr><th>Contrato</th><th>Número contrato</th><th>Ordem de compra</th><th>Data emissão</th><th>Fornecedor</th><th>Objeto - resumo</th><th>Valor total PO</th><th>Valor faturado PO</th><th>Saldo PO</th></tr></thead><tbody>${totalRow}${dataRows}</tbody></table>`; return reportMode?table:`<div class="contracts-table-wrap">${table}</div>`;}
function renderPoDetails(rows){const box=$('#contractPoDetails'); if(!box)return; const pos=poRowsForContracts(rows); box.style.display='block'; box.innerHTML=`<div class="contracts-table-toolbar"><h2>Detalhamento por PO</h2><span>${num(pos.length)} ordem(ns) de compra associada(s) aos contratos filtrados</span></div>${poDetailsTableHtml(rows,false)}`;}
function rowMatches(r,f,cat){const ordVal = cat==='finalisticos' ? r.tipoOrdenacao : r.ordenadorDespesa; const hay=[r.contrato,r.numero,r.empresa,r.objetoResumo,r.unidade,r.grandComando,r.acao,r.cage,ordVal].join(' ').toLowerCase(); return has(f.numero,r.numero)&&has(f.empresa,r.empresa)&&has(f.unidade,r.unidade)&&has(f.gc,r.grandComando)&&has(f.ordenador,ordVal)&&has(f.acao,r.acao)&&has(f.moeda,r.moeda)&&has(f.status,vigenciaBucket(r))&&has(f.valueRange,valueRangeBucket(r.valorContrato))&&(!f.search||hay.includes(f.search));}
function populateFilters(rows,cat){fillMulti($('#filterNumeroContrato'), unique(rows.map(r=>r.numero))); fillMulti($('#filterEmpresa'), unique(rows.map(r=>r.empresa))); fillMulti($('#filterUnidade'), unique(rows.map(r=>r.unidade))); fillMulti($('#filterGrandeComando'), unique(rows.map(r=>r.grandComando))); fillMulti($('#filterOrdenador'), cat==='finalisticos' ? ['Ordenação de despesas pela CABW','Ordenação de Despesas pela OM Requisitante'] : unique(rows.map(r=>r.ordenadorDespesa))); fillMulti($('#filterAcao'), unique(rows.map(r=>r.acao))); fillMulti($('#filterMoeda'), unique(rows.map(r=>r.moeda))); fillMulti($('#filterStatus'), ['Vencimento acima de 150 dias','Vencimento entre 90 e 150 dias','Vencimento em até 90 dias','Vigência expirada','Sem data final']); fillMulti($('#filterValueRange'), valueRangeOptions);}
function drawChart(rows){const el=$('#contractsValueChart'); if(!el)return; const a=agg(rows); if(window.Plotly){Plotly.newPlot(el,[{type:'bar',x:['Valor contratado','Empenhado','Faturado','Saldo empenhado a faturar','Disponível p/ empenho'],y:[a.value,a.paid,a.billed,a.toBill,a.available],text:[money(a.value),money(a.paid),money(a.billed),money(a.toBill),money(a.available)],textposition:'auto',marker:{color:['#003b7a','#0e63b6','#f5c400','#1f7a66','#4c6a92']}}],{height:390,margin:{l:80,r:20,t:20,b:105},yaxis:{title:'US$'},xaxis:{automargin:true,tickangle:-18}},{displayModeBar:false,responsive:true});}else{el.innerHTML='<p>Plotly não carregado.</p>';}}

async function getContractChartImage(){const el=$('#contractsValueChart'); if(!el||!window.Plotly||!el.data) return ''; try{return await Plotly.toImage(el,{format:'png',width:1000,height:460,scale:1.5});}catch(e){console.warn('Falha ao capturar gráfico',e); return '';}}

async function getInvoiceMonthlyChartImage(){const el=$('#contractsInvoiceMonthlyChart'); if(!el||!window.Plotly||!el.data) return ''; try{return await Plotly.toImage(el,{format:'png',width:1000,height:460,scale:1.5});}catch(e){console.warn('Falha ao capturar gráfico mensal',e); return '';}}
function contractReportStyles(){return `<style>body{font-family:Arial,Helvetica,sans-serif;color:#0a2450;margin:32px;}h1{font-size:28px;margin:0 0 6px;color:#00265f;}h2{font-size:18px;color:#00265f;border-bottom:2px solid #ffd200;padding-bottom:6px;margin-top:24px;}p{text-align:justify;line-height:1.45}.meta{color:#52627a;margin-bottom:18px}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:18px 0}.card{border:1px solid #d9e2ef;border-radius:12px;padding:12px;background:#f8fbff}.card span{display:block;font-size:12px;color:#52627a;font-weight:700}.card strong{display:block;font-size:18px;color:#00265f;margin-top:4px}.chart{width:100%;max-width:900px;margin:12px auto;display:block;border:1px solid #e1e8f2;border-radius:8px}.report-filter-table,table{border-collapse:collapse;width:100%;font-size:11px}.report-filter-table th{width:190px;text-align:left;background:#eef3fa}th,td{border:1px solid #d9e2ef;padding:6px;vertical-align:top}thead th{background:#003b7a;color:#fff}.po-total-row td,.po-total-row th{font-weight:800!important;background:#eef3fa!important;color:#00265f!important}.text-right{text-align:right}.risk{background:#fff5d6}.print-actions{position:sticky;top:0;background:#fff;padding:8px 0;margin-bottom:12px}.print-actions button{background:#003b7a;color:#fff;border:0;border-radius:8px;padding:10px 14px;font-weight:700}@media print{.print-actions{display:none}.chart{page-break-inside:avoid}body{margin:16mm}.cards{grid-template-columns:repeat(2,1fr)}table{font-size:9px}} </style>`;}
function contractSelectedFiltersHtml(){const rows=$all('.cabw-multi-dropdown').map(w=>{const label=w.closest('label')?.querySelector('span')?.textContent?.trim()||'Filtro'; const val=w.querySelector('.cabw-multi-button')?.textContent?.trim()||'Todas as opções'; return `<tr><th>${esc(label)}</th><td>${esc(val)}</td></tr>`;}); const search=$('#filterContratoSearch')?.value?.trim(); if(search) rows.push(`<tr><th>Busca geral</th><td>${esc(search)}</td></tr>`); return rows.length?`<table class="report-filter-table"><tbody>${rows.join('')}</tbody></table>`:'<p>Sem filtros específicos selecionados.</p>';}
async function generateContractsReport(){
  const cat=document.body.getAttribute('data-contract-category'); const base=catRows(cat); const f=filters(); const rows=base.filter(r=>rowMatches(r,f,cat)); const a=agg(rows); const chart=await getContractChartImage(); const invoiceChart=await getInvoiceMonthlyChartImage();
  const title=$('#contract-section-title')?.textContent?.trim()||'Contratos';
  const bodyRows=rows.map(r=>`<tr class="${risk(r)?'risk':''}"><td>${esc(r.contrato)}</td><td>${esc(r.numero)}</td><td>${esc(r.unidade)}</td><td>${esc(cat==='finalisticos'?r.tipoOrdenacao:r.ordenadorDespesa)}</td><td>${esc(r.grandComando)}</td><td>${esc(r.empresa)}</td><td>${esc(r.objetoResumo)}</td><td>${esc(r.moeda)}</td><td class="text-right">${money(r.valorContrato)}</td><td class="text-right">${money(r.totalEmpenhadoUsd)}</td><td class="text-right">${money(r.totalFaturadoUsd)}</td><td class="text-right">${money(r.valorAEmpenhar)}</td><td>${dateBr(r.dataFinal)}</td><td>${esc(vigenciaBucket(r))} ${risk(r)?risk(r):''}</td></tr>`).join('');
  const html=`<!doctype html><html><head><meta charset="utf-8"><title>Relatório - ${esc(title)}</title>${contractReportStyles()}</head><body><div class="print-actions"><button onclick="window.print()">Imprimir / salvar PDF</button></div><h1>Relatório Gerencial - ${esc(title)}</h1><div class="meta">Gerado em ${new Date().toLocaleString('pt-BR')} com base nos filtros aplicados no painel.</div><p>Este relatório apresenta os contratos filtrados, seus principais indicadores financeiros, situação de vigência e detalhamento gerencial para acompanhamento da execução contratual.</p><h2>Filtros aplicados</h2>${contractSelectedFiltersHtml()}<h2>Indicadores</h2><div class="cards"><div class="card"><span>Contratos</span><strong>${num(a.count)}</strong></div><div class="card"><span>Valor contratado</span><strong>${money(a.value)}</strong></div><div class="card"><span>Total empenhado USD</span><strong>${money(a.paid)}</strong></div><div class="card"><span>Total faturado USD</span><strong>${money(a.billed)}</strong></div></div><h2>Gráfico de valores</h2>${chart?`<img class="chart" src="${chart}">`:'<p>Gráfico indisponível.</p>'}<h2>Tabela detalhada de contratos</h2><table><thead><tr><th>Contrato</th><th>Número</th><th>Unidade</th><th>Ordenação</th><th>Grande Comando</th><th>Empresa</th><th>Objeto</th><th>Moeda</th><th>Valor</th><th>Empenhado USD</th><th>Faturado USD</th><th>Disp. empenho</th><th>Fim vigência</th><th>Vigência</th></tr></thead><tbody>${bodyRows||'<tr><td colspan="14">Nenhum contrato encontrado.</td></tr>'}</tbody></table><h2>Faturamento mensal por PO associada</h2>${invoiceChart?`<img class="chart" src="${invoiceChart}">`:'<p>Gráfico mensal indisponível.</p>'}<h2>Detalhamento por PO</h2>${poDetailsTableHtml(rows,true)}</body></html>`;
  const w=window.open('','_blank'); if(!w){alert('Autorize pop-ups para gerar o relatório.'); return;} w.document.open(); w.document.write(html); w.document.close();
}

function renderOverview(){const rootEl=document.querySelector('[data-contract-overview]'); if(!rootEl)return; const all=agg(records); $('[data-all-contracts-count]')&&($('[data-all-contracts-count]').textContent=num(all.count)); $('[data-all-contracts-paid]')&&($('[data-all-contracts-paid]').textContent=money(all.paid)+' empenhados'); $all('[data-contract-summary]').forEach(card=>{const cat=card.getAttribute('data-contract-summary'); const a=agg(catRows(cat)); $('[data-summary-count]',card)&&($('[data-summary-count]',card).textContent=num(a.count)); $('[data-summary-value]',card)&&($('[data-summary-value]',card).textContent=money(a.value)); $('[data-summary-paid]',card)&&($('[data-summary-paid]',card).textContent=money(a.paid));});}
function renderPanel(){const cat=document.body.getAttribute('data-contract-category'); if(!cat)return; const base=catRows(cat); $('#contract-section-title')&&($('#contract-section-title').textContent={administrativos:'Contratos Administrativos',finalisticos:'Contratos Finalísticos',fms:'FMS (Foreign Military Sales)'}[cat]||'Contratos'); populateFilters(base,cat); function refresh(){const f=filters(); const rows=base.filter(r=>rowMatches(r,f,cat)); const a=agg(rows); $('[data-kpi="count"]')&&($('[data-kpi="count"]').textContent=num(a.count)); $('[data-kpi="value"]')&&($('[data-kpi="value"]').textContent=money(a.value)); $('[data-kpi="paidUsd"]')&&($('[data-kpi="paidUsd"]').textContent=money(a.paid)); $('[data-kpi="billedUsd"]')&&($('[data-kpi="billedUsd"]').textContent=money(a.billed)); const count=$('#contractsTableCount'); if(count) count.textContent=num(rows.length)+' contrato(s)'; const tb=$('#contractsTable tbody'); if(tb) tb.innerHTML=rows.map(r=>`<tr class="${risk(r)?'contract-risk-row':''}"><td>${esc(r.contrato)}</td><td>${esc(r.numero)}</td><td>${esc(r.unidade)}</td><td>${esc(cat==='finalisticos'?r.tipoOrdenacao:r.ordenadorDespesa)}</td><td>${esc(r.grandComando)}</td><td>${esc(r.empresa)}</td><td class="contracts-object-cell">${esc(r.objetoResumo)}</td><td>${esc(r.moeda)}</td><td class="text-right">${money(r.valorContrato)}</td><td class="text-right">${money(r.totalEmpenhadoUsd)}</td><td class="text-right">${money(r.totalFaturadoUsd)}</td><td class="text-right">${money(r.valorAEmpenhar)}</td><td>${dateBr(r.dataFinal)}</td><td>${esc(vigenciaBucket(r))} ${risk(r)?'<strong class="risk-flag">'+risk(r)+'</strong>':''}</td></tr>`).join(''); drawChart(rows); drawInvoiceMonthlyChart(rows); renderPoDetails(rows);} $all('#filterNumeroContrato,#filterEmpresa,#filterUnidade,#filterGrandeComando,#filterOrdenador,#filterAcao,#filterMoeda,#filterStatus,#filterValueRange').forEach(el=>el.addEventListener('change',refresh)); $('#filterContratoSearch')?.addEventListener('input',refresh); $('#resetContractFilters')?.addEventListener('click',()=>{ $all('#filterNumeroContrato,#filterEmpresa,#filterUnidade,#filterGrandeComando,#filterOrdenador,#filterAcao,#filterMoeda,#filterStatus,#filterValueRange').forEach(sel=>Array.from(sel.options).forEach(o=>o.selected=false)); updateAllCabwMultis(); if($('#filterContratoSearch'))$('#filterContratoSearch').value=''; refresh();}); $('#generateContractsReport')?.addEventListener('click',generateContractsReport); refresh();}
document.addEventListener('DOMContentLoaded',()=>{try{renderOverview();renderPanel();}catch(e){console.error('CABW contracts panel error',e);}});
})();
