// rp-panel.js
(function(){
  const root=window.CABW_RP_DATA||{records:window.rpData||window.RP_DATA||[],summary:window.RP_SUMMARY||{}}; const rows=Array.isArray(root.records)?root.records:[]; const summary=root.summary||{};
  const $=s=>document.querySelector(s); const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'USD'}).format(Number(v||0));
  function uniq(a){return [...new Set(a.filter(Boolean))].sort((x,y)=>String(x).localeCompare(String(y),'pt-BR'));}
  function fill(sel, vals, label){const e=$(sel); if(!e)return; e.innerHTML='<option value="">'+label+'</option>'+vals.map(v=>'<option>'+escapeHtml(v)+'</option>').join('');}
  function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
  function filtered(){const y=$('#rpYearFilter')?.value||'', om=$('#rpOmFilter')?.value||'', c=$('#rpContractFilter')?.value||'', emp=($('#rpEmpenhoFilter')?.value||'').toLowerCase(), q=($('#rpSearchFilter')?.value||'').toLowerCase(); return rows.filter(r=>(!y||r.ano===y)&&(!om||r.om===om)&&(!c||r.contratoPag===c)&&(!emp||String(r.empenho).toLowerCase().includes(emp))&&(!q||[r.om,r.contratoPag,r.empenho,r.credor,r.objeto,r.acao,r.natureza,r.projeto].join(' ').toLowerCase().includes(q)));}
  function agg(arr, key){const m={}; arr.forEach(r=>{const k=r[key]||'Não informado'; if(!m[k])m[k]={label:k,saldo:0,empenhos:new Set(),contratos:new Set(),oms:new Set()}; m[k].saldo+=Number(r.saldoUsd||0); m[k].empenhos.add(r.empenho); m[k].contratos.add(r.contratoPag); m[k].oms.add(r.om);}); return Object.values(m).sort((a,b)=>b.saldo-a.saldo);}
  function plot(id, data, title){if(!window.Plotly||!$(id))return; Plotly.newPlot(id,[{type:'bar',orientation:'h',y:data.slice(0,15).map(x=>x.label).reverse(),x:data.slice(0,15).map(x=>x.saldo).reverse(),text:data.slice(0,15).map(x=>money(x.saldo)).reverse(),textposition:'auto',hovertemplate:'%{y}<br>%{text}<extra></extra>'}],{title,margin:{l:160,r:20,t:50,b:40},height:420,xaxis:{tickprefix:'US$ '}},{displayModeBar:false,responsive:true});}
  function renderTable(sel, data, kind){const tb=$(sel); if(!tb)return; tb.innerHTML=data.slice(0,100).map(x=> kind==='year'?`<tr><td>${escapeHtml(x.label)}</td><td class="text-right">${money(x.saldo)}</td><td class="text-center">${x.oms.size}</td><td class="text-center">${x.contratos.size}</td><td class="text-center">${x.empenhos.size}</td></tr>`:`<tr><td>${escapeHtml(x.label)}</td><td class="text-right">${money(x.saldo)}</td><td class="text-center">${kind==='om'?x.contratos.size:x.oms.size}</td><td class="text-center">${x.empenhos.size}</td></tr>`).join('');}
  function render(){const f=filtered(); const saldo=f.reduce((s,r)=>s+Number(r.saldoUsd||0),0); const set=k=>new Set(f.map(r=>r[k]).filter(Boolean)).size; $('#rpSourceInfo')&&( $('#rpSourceInfo').textContent='Fonte: '+(summary.sourceFile||'dados RP')+' · '+f.length+' registros filtrados'); $('#rpRowsInfo')&&($('#rpRowsInfo').textContent=f.length+' registros encontrados'); $('#rpKpiSaldo')&&($('#rpKpiSaldo').textContent=money(saldo)); $('#rpKpiOms')&&($('#rpKpiOms').textContent=set('om')); $('#rpKpiContratos')&&($('#rpKpiContratos').textContent=set('contratoPag')); $('#rpKpiAnos')&&($('#rpKpiAnos').textContent=set('ano')); $('#rpKpiEmpenhos')&&($('#rpKpiEmpenhos').textContent=set('empenho')); const byOm=agg(f,'om'), byC=agg(f,'contratoPag'), byY=agg(f,'ano'); plot('#rpOmChart',byOm,'Saldo de RP por OM'); plot('#rpContractChart',byC,'Saldo de RP por Contrato/PAG'); plot('#rpYearChart',byY,'Saldo de RP por Ano'); renderTable('#rpOmSummaryBody',byOm,'om'); renderTable('#rpContractSummaryBody',byC,'contract'); renderTable('#rpYearSummaryBody',byY,'year'); const det=$('#rpDetailBody'); if(det) det.innerHTML=f.slice(0,300).map(r=>`<tr><td>${escapeHtml(r.ano)}</td><td>${escapeHtml(r.om)}</td><td>${escapeHtml(r.contratoPag)}</td><td>${escapeHtml(r.empenho)}</td><td>${escapeHtml(r.credor)}</td><td>${escapeHtml(r.objeto)}</td><td class="text-right">${money(r.saldoUsd)}</td></tr>`).join('');}
  document.addEventListener('DOMContentLoaded',()=>{fill('#rpYearFilter',uniq(rows.map(r=>r.ano)),'Todos os anos'); fill('#rpOmFilter',uniq(rows.map(r=>r.om)),'Todas as OMs'); fill('#rpContractFilter',uniq(rows.map(r=>r.contratoPag)),'Todos os contratos/PAG'); ['#rpYearFilter','#rpOmFilter','#rpContractFilter','#rpEmpenhoFilter','#rpSearchFilter'].forEach(s=>$(s)&&$(s).addEventListener($(s).tagName==='INPUT'?'input':'change',render)); $('#rpClearFilters')&&$('#rpClearFilters').addEventListener('click',()=>{['#rpYearFilter','#rpOmFilter','#rpContractFilter','#rpEmpenhoFilter','#rpSearchFilter'].forEach(s=>{if($(s))$(s).value='';});render();}); $('#rpGeneratePdf')&&$('#rpGeneratePdf').addEventListener('click',()=>{if(!window.jspdf){alert('Biblioteca PDF não carregada.');return;} const doc=new jspdf.jsPDF('l','pt','a4'); doc.text('Painel CABW - RP',40,40); doc.autoTable({startY:60,head:[['Ano','OM','Contrato/PAG','Empenho','Credor','Saldo RP']],body:filtered().map(r=>[r.ano,r.om,r.contratoPag,r.empenho,r.credor,money(r.saldoUsd)]),styles:{fontSize:7}}); doc.save('rp-cabw.pdf');}); render();});
})();
