
(function(){'use strict';
const data=window.CABW_SUPRIMENTO_DATA||{orders:[],digits:[],summary:{}}; const $=(s,c)=> (c||document).querySelector(s); const $$=(s,c)=>Array.from((c||document).querySelectorAll(s));
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])); const money=v=>'US$ '+Number(v||0).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}); const num=v=>Number(v||0).toLocaleString('pt-BR');
function unique(a){return [...new Set(a.filter(x=>x!==undefined&&x!==null&&String(x).trim()!==''))].sort((a,b)=>String(a).localeCompare(String(b),'pt-BR'));}
function selected(sel){return sel?Array.from(sel.selectedOptions).map(o=>o.value).filter(Boolean):[];}
function installCss(){if($('#sfCss'))return; const st=document.createElement('style'); st.id='sfCss'; st.textContent='.sf-filter-grid{display:grid;grid-template-columns:repeat(3,minmax(240px,1fr));gap:16px}.sf-field span{font-weight:800;color:#00265f;font-size:13px}.sf-field select{width:100%;min-height:42px;border:1px solid #ccd6e6;border-radius:10px;background:#f8fbff;padding:8px}.sf-kpi-grid{display:grid;grid-template-columns:repeat(4,minmax(180px,1fr));gap:16px;margin:18px 0}.sf-kpi{background:#fff;border:1px solid #d9e2ef;border-radius:14px;padding:16px;box-shadow:0 8px 22px rgba(0,31,85,.07)}.sf-kpi span{display:block;font-size:12px;color:#52627a;font-weight:800;text-transform:uppercase}.sf-kpi strong{display:block;font-size:20px;color:#00265f;margin-top:6px}.sf-card{background:#fff;border:1px solid #d9e2ef;border-radius:16px;padding:18px;margin:18px 0;box-shadow:0 12px 28px rgba(0,31,85,.08)}.sf-grid-2{display:grid;grid-template-columns:1fr 1fr;gap:18px}.sf-table{width:100%;border-collapse:collapse;font-size:13px}.sf-table th{background:#003b7a;color:#fff}.sf-table th,.sf-table td{border:1px solid #d9e2ef;padding:8px;vertical-align:top}.text-right{text-align:right}@media(max-width:1100px){.sf-filter-grid,.sf-grid-2{grid-template-columns:1fr}.sf-kpi-grid{grid-template-columns:repeat(2,1fr)}}'; document.head.appendChild(st);}
function valRange(v){v=Number(v||0); if(v<=1000)return 'até US$ 1,000.00'; if(v<=5000)return 'entre US$ 1,000.00 e US$ 5,000.00'; if(v<=10000)return 'entre US$ 5,000.00 e US$ 10,000.00'; return 'acima de US$ 10,000.00';}
function fill(id, vals){const el=$(id); if(!el)return; const old=selected(el); el.multiple=true; el.innerHTML=vals.map(v=>'<option value="'+esc(v)+'">'+esc(v)+'</option>').join(''); old.forEach(v=>{const o=[...el.options].find(o=>o.value===v); if(o)o.selected=true;});}
function filters(){return {emp:selected($('#sfEmpresa')), faixa:selected($('#sfFaixa')), nat:selected($('#sfNatureza')), sub:selected($('#sfSubelemento')), ano:selected($('#sfAno'))};}
function rows(){const f=filters(); return (data.orders||[]).filter(r=>(!f.emp.length||f.emp.includes(r.empresaLabel))&&(!f.faixa.length||f.faixa.includes(valRange(r.valorTotalUsd)))&&(!f.nat.length||f.nat.includes(r.natureza))&&(!f.sub.length||f.sub.includes(r.subelemento))&&(!f.ano.length||f.ano.includes(String(r.ano))));}
function groupByEmpresa(rs){const m={}; rs.forEach(r=>{const k=r.empresaLabel||'N/I'; (m[k]||(m[k]={emp:0,fat:0,sal:0})); m[k].emp+=Number(r.valorTotalUsd||0); m[k].fat+=Number(r.valorFaturadoUsd||0); m[k].sal+=Number(r.saldoUsd||0);}); return Object.entries(m).map(([label,v])=>({label,...v})).sort((a,b)=>b.emp-a.emp).slice(0,25).reverse();}
function draw(rs){const by=groupByEmpresa(rs); if(window.Plotly&&$('#sfEmpresasChart')) Plotly.newPlot($('#sfEmpresasChart'),[{type:'bar',orientation:'h',name:'Empenhado não faturado',y:by.map(x=>x.label),x:by.map(x=>x.sal),marker:{color:'#003b7a'},text:by.map(x=>money(x.sal)),textposition:'auto'},{type:'bar',orientation:'h',name:'Faturado',y:by.map(x=>x.label),x:by.map(x=>x.fat),marker:{color:'#f5c400'},text:by.map(x=>money(x.fat)),textposition:'auto'}],{height:Math.max(400,by.length*30+100),barmode:'stack',margin:{l:220,r:25,t:35,b:45},xaxis:{title:'US$'},legend:{orientation:'h',x:0,y:1.12}},{displayModeBar:false,responsive:true}); const fat=rs.reduce((a,r)=>a+Number(r.valorFaturadoUsd||0),0), sal=rs.reduce((a,r)=>a+Number(r.saldoUsd||0),0); if(window.Plotly&&$('#sfPizzaChart')) Plotly.newPlot($('#sfPizzaChart'),[{type:'pie',labels:['Empenhado e faturado','Empenhado e não faturado'],values:[fat,sal],textinfo:'label+percent',marker:{colors:['#f5c400','#003b7a']}}],{height:380,margin:{l:20,r:20,t:30,b:20}},{displayModeBar:false,responsive:true});}
function render(){const rs=rows(); const credito=(data.digits||[]).reduce((a,r)=>a+Number(r.saldo||0),0); $('#sfCredito')&&($('#sfCredito').textContent=money(credito)); $('#sfEmpAno')&&($('#sfEmpAno').textContent=money(rs.reduce((a,r)=>a+Number(r.valorTotalUsd||0),0))); $('#sfSaldo')&&($('#sfSaldo').textContent=money(rs.reduce((a,r)=>a+Number(r.saldoUsd||0),0))); $('#sfReq')&&($('#sfReq').textContent=num((data.summary||{}).totalRequisicoes||0)); $('#sfPessoas')&&($('#sfPessoas').textContent=num(unique(rs.map(r=>r.empresaCodigo)).length)); draw(rs); const tb=$('#sfTable tbody'); if(tb)tb.innerHTML=rs.slice().sort((a,b)=>String(b.data||'').localeCompare(String(a.data||''))).map(r=>'<tr><td>'+esc(r.po)+'</td><td>'+esc(r.data)+'</td><td>'+esc(r.empresaLabel)+'</td><td>'+esc(r.natureza)+'</td><td>'+esc(r.subelemento)+'</td><td class="text-right">'+money(r.valorTotalUsd)+'</td><td class="text-right">'+money(r.valorFaturadoUsd)+'</td><td class="text-right">'+money(r.saldoUsd)+'</td></tr>').join('')||'<tr><td colspan="8">Nenhuma ordem de compra encontrada.</td></tr>';}
document.addEventListener('DOMContentLoaded',()=>{installCss(); fill('#sfEmpresa',unique((data.orders||[]).map(r=>r.empresaLabel))); fill('#sfFaixa',['até US$ 1,000.00','entre US$ 1,000.00 e US$ 5,000.00','entre US$ 5,000.00 e US$ 10,000.00','acima de US$ 10,000.00']); fill('#sfNatureza',unique((data.orders||[]).map(r=>r.natureza))); fill('#sfSubelemento',unique((data.orders||[]).map(r=>r.subelemento))); fill('#sfAno',unique((data.orders||[]).map(r=>String(r.ano)))); $$('#sfEmpresa,#sfFaixa,#sfNatureza,#sfSubelemento,#sfAno').forEach(e=>e.addEventListener('change',render)); $('#sfClear')?.addEventListener('click',()=>{$$('#sfEmpresa,#sfFaixa,#sfNatureza,#sfSubelemento,#sfAno').forEach(s=>[...s.options].forEach(o=>o.selected=false)); render();}); render();});
})();
